### ISSUE TITLE
Warriors Orochi 3 Hyper

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#10]
## Description
[log.txt](https://github.com/user-attachments/files/17774348/log.txt)
the characters are only partially rendered.

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 11 44 36" src="https://github.com/user-attachments/assets/30cc2f7c-01fa-4a3d-abe4-f6c38af10396">
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 11 44 45" src="https://github.com/user-attachments/assets/79d92347-916e-4aee-8ff7-4191fbe2b72c">

Infame = https://www.mediafire.com/file/za6q31ulcrt60yy/WO3H.gputrace.zip/file
Please include at least one screenshot of the game (if possible).

## Cemu Metal version
hyrule warriors test build
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Could you please try out with the latest build? The Hyrule Warriors build has a hack that could cause some games to not render some geometry.

**Comment by darkuser89** [comment]
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 19 51 19" src="https://github.com/user-attachments/assets/b45b4425-d1af-4a25-a88b-d03643862dbc">
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 19 52 06" src="https://github.com/user-attachments/assets/2922075e-d069-4cd9-8716-79499b11ce52">
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 19 52 15" src="https://github.com/user-attachments/assets/cd6c2a53-2929-4e57-929e-e2a6e84ba5e2">

yes with version 1.0.3 it works better only when you attack the opponents the character and the opponents become black

**Comment by SamoZ256** [comment]
[The wiki](https://wiki.cemu.info/wiki/Warriors_Orochi_3_Hyper) says that the issue with opponents turning black is on other platforms as well, so closing this.
