### ISSUE TITLE
Transformers Prime

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#11]
## Description
Perfect

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-16 um 18 08 20" src="https://github.com/user-attachments/assets/80845c0d-a5d1-4cac-87a3-9a45977caa23">
<img width="1260" alt="Bildschirmfoto 2024-11-16 um 18 14 58" src="https://github.com/user-attachments/assets/581da62d-bd4d-45b7-b002-d55ee5bf39e1">

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.4

Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Nice, finally a game that runs perfectly 😅
