### ISSUE TITLE
SONIC LOST WORLD

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#14]
## Description
Playable
[log.txt](https://github.com/user-attachments/files/17814477/log.txt)
it seems that the lighting is missing the picture is too dark
Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-19 um 12 31 04" src="https://github.com/user-attachments/assets/9b3512d7-fc50-42b8-b34f-796ad946531b">
<img width="1260" alt="Bildschirmfoto 2024-11-19 um 12 31 17" src="https://github.com/user-attachments/assets/078c373a-c840-4620-8048-4ea53fe0f937">

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.4
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Seems like the issue is on Windows as well (according to the [wiki](https://wiki.cemu.info/wiki/Sonic_Lost_World)).
