### ISSUE TITLE
Deus Ex: Human Revolution - Director's Cut

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#16]
## Description
Boot
emulator crashes when you enter the door code in the first level
[log.txt](https://github.com/user-attachments/files/17820106/log.txt)

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-19 um 20 06 33" src="https://github.com/user-attachments/assets/087d8a52-240e-474f-a259-14f35eac20f9">
<img width="1260" alt="Bildschirmfoto 2024-11-19 um 20 06 47" src="https://github.com/user-attachments/assets/e72d0ac0-391d-4a44-97f0-70939d401f5b">

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.05
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by shinra-electric** [comment]
Can you re-test with `1.0.9`? 

I got a crash initially, but now it works every time. (Maybe a bad shader in the shader cache...?)

![Screenshot 2024-12-11 at 12 28 06](https://github.com/user-attachments/assets/5d5e42e2-97b3-4a80-8397-e35deded5580)
![Screenshot 2024-12-11 at 12 29 03](https://github.com/user-attachments/assets/94199a17-4b44-479d-89bf-dda234bd1ac0)

**Comment by SamoZ256** [comment]
@shinra-electric did the initial crash happen on 1.0.9?

**Comment by shinra-electric** [comment]
It crashed on me with a previous version, then crashed on my first run with 1.0.9.
But I haven't been able to replicate the crash since then.

**Comment by shinra-electric** [comment]
I just deleted my shader cache and went through again on `1.0.9`. 
No crash.

**Comment by SamoZ256** [comment]
Are there any remaining issues in this game? If the crash cannot be reproduced anymore, I guess it was just a coincidence caused by switching to a newer version

**Comment by darkuser89** [comment]
yes looks good works

**Comment by SamoZ256** [comment]
Okay, closing this 👍
