### ISSUE TITLE
Resident Evil: Revelations

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#17]
## Description
Playable
[log.txt](https://github.com/user-attachments/files/17820348/log.txt)
only small black spots
Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1216" alt="Bildschirmfoto 2024-11-19 um 20 21 55" src="https://github.com/user-attachments/assets/84326ce2-b0c7-417f-9226-9910e206a56e">
<img width="1216" alt="Bildschirmfoto 2024-11-19 um 20 25 27" src="https://github.com/user-attachments/assets/f9ffe28f-2647-4d27-b3ce-0e0206004f8b">
<img width="1216" alt="Bildschirmfoto 2024-11-19 um 20 27 54" src="https://github.com/user-attachments/assets/021353fd-764b-4e23-ba61-d55de66749c6">
Here you can see that it happens with some objects when you approach them

https://github.com/user-attachments/assets/61855557-11f4-4be7-b22b-f9e4a862139e

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.5
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by darkuser89** [comment]
:-) Resident evil is fixed "Depth bias hack"
<img width="1159" alt="Bildschirmfoto 2024-12-16 um 20 55 48" src="https://github.com/user-attachments/assets/bf21e777-a94e-406e-a9e3-2b6dde4d7775" />
<img width="1159" alt="Bildschirmfoto 2024-12-16 um 20 59 45" src="https://github.com/user-attachments/assets/fe85ded3-96e5-450a-b5b0-676e59c139c2" />
<img width="1159" alt="Bildschirmfoto 2024-12-16 um 21 01 29" src="https://github.com/user-attachments/assets/975482af-1170-4b3b-8698-7279f6710699" />

**Comment by SamoZ256** [comment]
Nice :)
