### ISSUE TITLE
ZombiU

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#20]
## Description
Boot
Blackscreen
Unfortunately doesn't work on Windows either
Describe the issues with the game (`Perfect` if none).

## Screenshots
https://www.mediafire.com/file/xp0qqwdvzezm2tb/Cemu_release.gputrace.zip/file

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.5
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
I read the Cemu wiki and it seems like you can get it to work by uninstalling the update

**Comment by darkuser89** [comment]
I read that too but without update the game doesn't start with update it starts

**Comment by SamoZ256** [comment]
And on Windows you get the same black screen?

**Comment by darkuser89** [comment]
windows starts with and without update but both have the black screen
