### ISSUE TITLE
The Amazing Spider-Man

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#22]
## Description
boot
only shows black picture, videos and menu run in the background
Describe the issues with the game (`Perfect` if none).

## Screenshots
https://www.mediafire.com/file/ywu0pe5z6ljx4il/Cemu_release.gputrace.zip/file

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.5
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by darkuser89** [comment]
Yes that's it

**Comment by SamoZ256** [comment]
Do you have a log? It seems like it just doesn't present the final image

**Comment by darkuser89** [comment]
[log.txt](https://github.com/user-attachments/files/17834278/log.txt)
