### ISSUE TITLE
Child of Light

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#24]
## Description

`Perfect`

## Screenshots
<img width="1392" alt="Screenshot 2024-11-20 at 17 21 43" src="https://github.com/user-attachments/assets/5e296068-621a-4ac6-a662-f76e09017544">

## Cemu Metal version

`testing1.0.5`

## Mac

MacBook Pro
M1 Pro 
macOS Sequoia 15.1.1

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
Nice :)
