### ISSUE TITLE
Ninja Gaiden 3: Razor's Edge

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#26]
## Description
`Playable`

Black flickering on character's skin during cutscenes. Also affects Vulkan. 

## Screenshots
<img width="1392" alt="Screenshot 2024-11-20 at 17 32 48" src="https://github.com/user-attachments/assets/7a6d3da4-4545-4edf-a02b-b162fff1f388">

## Cemu Metal version

`testing1.0.5`

## Mac
MacBook Pro
M1 Pro
macOS 15.1.1 Sequoia

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
Could you please do a frame capture for the black spots?

**Comment by shinra-electric** [comment]
This isn't the best frame capture, because it looks as if it's fine. But if you look closely you can see the black spots. They normally flicker all over the face. 

This was captured on 1.0.9, not with the depth bias patch build. 

https://file.io/xkaZbPYGgNer

**Comment by shinra-electric** [comment]
Tried with the depth bias hack:
<img width="1392" alt="Screenshot 2024-12-17 at 17 25 12" src="https://github.com/user-attachments/assets/36506db3-b63c-4176-bb1b-ab12a5aab4fc" />
<img width="1392" alt="Screenshot 2024-12-17 at 17 25 23" src="https://github.com/user-attachments/assets/e0892291-b112-48e2-a246-831bbbde7980" />

**Comment by SamoZ256** [comment]
@shinra-electric [this build](https://drive.google.com/file/d/1BjgXDme8r4XZszjl-MIKBTEr1MBWdw22/view?usp=sharing) should hopefully work. The depth bias hack does not exist anymore, it was replaced with "position invariance" (in the game profile as well).

**Comment by shinra-electric** [comment]
The position invariance option fixes the issue:

<img width="1392" alt="Screenshot 2024-12-18 at 15 58 52" src="https://github.com/user-attachments/assets/b699dfde-401d-4ee0-ace0-17c4ff90d73d" />
<img width="1392" alt="Screenshot 2024-12-18 at 15 59 01" src="https://github.com/user-attachments/assets/2760b103-6d9f-4e40-b924-636c5e178263" />

**Comment by SamoZ256** [comment]
Nice! Are there any other issues in the game?

**Comment by shinra-electric** [comment]
I can't see any graphical issues. 

Technically perfect, but It can drop to as low as 30fps when in battle, making it hard to play (should be 60fps), but Vulkan is the same.
