### ISSUE TITLE
One Piece: Unlimited World Red

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#27]
## Description
`Perfect`

## Screenshots
<img width="1392" alt="Screenshot 2024-11-20 at 18 14 29" src="https://github.com/user-attachments/assets/3520a757-bca2-4b7a-9990-7f30a85bfe8b">

## Cemu Metal version
`testing1.0.5`

## Mac
M1 Pro
macOS Sequoia 15.1.1

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
Nice
