### ISSUE TITLE
Devil's Third

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#29]
## Description
`In-game`
Character models are all black. Same issue on Vulkan.

## Screenshots
![Screenshot 2024-11-20 at 18 55 44](https://github.com/user-attachments/assets/a9bc3d62-4538-4916-bd6b-6cc461b0e506)

## Cemu Metal version
`testing1.0.5`

## Mac
M1 Pro
macOS Sequoia 15.1.1

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
Could you please make a frame capture?

**Comment by shinra-electric** [comment]
https://file.io/ThYP0ZRt2VyB

**Comment by SamoZ256** [comment]
@shinra-electric could you please send a log?

**Comment by shinra-electric** [comment]
[log.txt](https://github.com/user-attachments/files/18051964/log.txt)

**Comment by SamoZ256** [comment]
[This build](https://drive.google.com/file/d/1lrTK2GDtkrrtJvz6QIF7VHyXu3D6C_Bp/view?usp=sharing) could fix it

**Comment by shinra-electric** [comment]
That build fixes it, though the performance took a dive...
![Screenshot 2024-12-08 at 13 46 52](https://github.com/user-attachments/assets/f924e3be-dcc5-455b-bed5-152258f37d78)

**Comment by SamoZ256** [comment]
That's great! The performance hit is understandable, since it wasn't rendering the character at all. Also, are there any other issues?

**Comment by shinra-electric** [comment]
(I assumed because it was a debug build or something...)

I can't see any other issues after playing for a few minutes. This could be another one for the `Perfect` pile after the fix is merged.

**Comment by SamoZ256** [comment]
Okay, I will label this as perfect.

**Comment by shinra-electric** [comment]
I just noticed another regression compared to Vulkan with this game. 

When you are hit by an enemy, there is a red bloodstain applied to the screen indicating the direction of where the attack came from. 

In Metal, the game screen turns black underneath the overlay:

![Image](https://github.com/user-attachments/assets/832e83ee-c08d-470b-99f8-075b67c39cdb)

In Vulkan it's fine (except for the black characters):

![Image](https://github.com/user-attachments/assets/b291dacb-f3bb-4f46-be2e-3f2894e126a4)


[GPU trace](https://limewire.com/d/ee891d3f-10cc-4a26-9617-4ed7a1cd5472#kIs-D4uBrghypUeGcO9HnZGROroXMoYvnas3f3VRckc)

**Comment by shinra-electric** [comment]
This is actually a regression

The version I was using above was the [special build](https://github.com/SamoZ256/cemu-metal-game-compatibility/issues/99#issuecomment-2600771778) that fixes Mass Effect 3.

It works on 2.2.0

![Image](https://github.com/user-attachments/assets/dda1988f-e116-4ecb-938a-0d655a67bd35)

**Comment by shinra-electric** [comment]
The above regression was fixed in a build provided on Discord.
