### ISSUE TITLE
Hello Kitty Kruisers

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#32]
## Description

Perfect

## Screenshots

<img width="1260" alt="Bildschirmfoto 2024-11-21 um 20 49 54" src="https://github.com/user-attachments/assets/e2e32694-0931-475f-ad53-4dcea22ce573">
<img width="1260" alt="Bildschirmfoto 2024-11-21 um 20 50 56" src="https://github.com/user-attachments/assets/db83fe87-227c-4626-9eac-04debe8fa9fe">

## Cemu Metal version

testing1.0.5

## Mac

M3 Pro MacBook Pro
11 CPU
14 GPU
18 GB RAM
MacOS 15.1.1 (24B91)

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Yet another perfect game :)
