### ISSUE TITLE
Ben 10 Omniverse 2

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#34]
## Description

`Perfect`

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-23 um 09 52 56" src="https://github.com/user-attachments/assets/1c4a9cbb-06d6-481a-8633-151fa7754e4e">
<img width="1260" alt="Bildschirmfoto 2024-11-23 um 09 53 47" src="https://github.com/user-attachments/assets/8feae027-5f75-4c1c-be91-70606318d041">

## Cemu Metal version

testing1.0.5

## Mac

M3 Pro MaBook Pro

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Nice ;)
