### ISSUE TITLE
 Fast & Furious: Showdown

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#35]
## Description

`Perfect`

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-23 um 13 59 19" src="https://github.com/user-attachments/assets/980c18be-80a5-47ed-98d6-82635ce1eb83">
<img width="1260" alt="Bildschirmfoto 2024-11-23 um 14 02 54" src="https://github.com/user-attachments/assets/fe7ad9cd-45fe-4a82-978a-68582bcd43ed">
<img width="1260" alt="Bildschirmfoto 2024-11-23 um 14 08 52" src="https://github.com/user-attachments/assets/26238247-6d20-42d3-adf2-2b8fdeff3036">

## Cemu Metal version

`testing1.0.5`

## Mac

M3 Pro MacBook Pro

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Let's go :)
