### ISSUE TITLE
Barbie and Her Sisters Puppy Rescue

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#42]
## Description

`Perfect`
Only in the 2 videos at the beginning is there a green stripe at the bottom. (also on Windows)

## Screenshots
<img width="1239" alt="Bildschirmfoto 2024-11-24 um 02 07 11" src="https://github.com/user-attachments/assets/a2d21b6b-1cb4-4be7-a8b7-7e865eadc6ca">
<img width="1239" alt="Bildschirmfoto 2024-11-24 um 02 10 25" src="https://github.com/user-attachments/assets/5906ab04-ff4c-43ac-b8f8-937e503dbc84">

## Cemu Metal version

`testing1.0.6`

## Mac

M3 Pro MacBook Pro

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
👍
