### ISSUE TITLE
Super Mario 3D World

### ISSUE THREAD

**Issue by bloedmage** [SamoZ256/cemu-metal-game-compatibility#44]
## Description

Seems almost perfect, played for 15 minutes. Only incorrect shadows on Mario when standing under something.

## Screenshots

![Screenshot 2024-11-24 at 12 55 57](https://github.com/user-attachments/assets/26943257-738e-465d-88c7-dcb966789be8)
![Screenshot 2024-11-24 at 13 00 38](https://github.com/user-attachments/assets/db71f4a6-ec1a-421b-becf-e9b0ea185610)

## Cemu Metal version

Cemu testing1.0.6

## Mac

Mac Pro 2013 running macOS Ventura 13.7.1 using OpenCore Legacy Patcher

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet.

**Comment by SamoZ256** [comment]
What is open core legacy patcher?

**Comment by bloedmage** [comment]
> What is open core legacy patcher?

It's a custom boot loader to install modern versions of macOS on unsupported Macs. In this case it also installs older Legacy GCN metal drivers not otherwise present in Ventura. I think it would only results in compatibility problems for metal 3 specific features.

**Comment by SamoZ256** [comment]
Regarding the shadow issue: it's hard to see from an image, but I looked up 3d world online and it seems to happen on a real Wii U as well. It's probably just some object above whose shadow reaches the floor. From the image it seems like the shadows have more issues, but I checked on my machine and it looks fine, so either it's because of your computer or everything is fine and the image is just a bit misleading.

**Comment by bloedmage** [comment]
> Regarding the shadow issue: it's hard to see from an image, but I looked up 3d world online and it seems to happen on a real Wii U as well. It's probably just some object above whose shadow reaches the floor. From the image it seems like the shadows have more issues, but I checked on my machine and it looks fine, so either it's because of your computer or everything is fine and the image is just a bit misleading.

One more screenshot showing the shadow bug more clearly. This time on my 2020 intel MacBook Pro 13 inch with intel graphics. 

![Screenshot 2024-11-24 at 23 29 54](https://github.com/user-attachments/assets/28c3e6ce-15fc-499c-a088-61cf91d5c4e7)

**Comment by SamoZ256** [comment]
Oh, that looks pretty bad. I still haven’t tried running on my Intel Mac with an AMD GPU.

**Comment by SamoZ256** [comment]
I checked on an Intel Mac with AMD GPU and I didn't see issues like that
