### ISSUE TITLE
Paper Mario Color Splash

### ISSUE THREAD

**Issue by bloedmage** [SamoZ256/cemu-metal-game-compatibility#45]
## Description

Played for 15 minutes, graphics seem perfect. Performance is not the best, but that might be fixed by a faster Mac. 
This game would only show a black screen with some visible 2D elements with MoltenVK.

## Screenshots

![Screenshot 2024-11-24 at 13 10 53](https://github.com/user-attachments/assets/d7d0e014-f50e-4724-8448-bf91a0a02af9)
![Screenshot 2024-11-24 at 13 22 47](https://github.com/user-attachments/assets/d662b388-190e-4012-ba15-e338f4c49855)

## Cemu Metal version

Cemu testing1.0.6

## Mac

Mac Pro 2013 running macOS Ventura 13.7.1 using OpenCore Legacy Patcher

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet.

**Comment by SamoZ256** [comment]
I have noticed performance drops, but idk if there’s much I can do about it
