### ISSUE TITLE
Legend of Zelda: Wind Waker HD

### ISSUE THREAD

**Issue by bloedmage** [SamoZ256/cemu-metal-game-compatibility#49]
## Description

Game looks and plays great. Played only couple of minutes. Only issue is the gamepad view is slightly darker than the main screen. 

## Screenshots

![Screenshot 2024-11-24 at 15 47 22](https://github.com/user-attachments/assets/30bee6c6-800c-40fd-a19d-679d4d503314)
![Screenshot 2024-11-24 at 15 55 46](https://github.com/user-attachments/assets/cc93d101-ed91-4244-bf4c-b140511be26c)

Using MoltenVK the gamepad view is the same as the main screen.
![Screenshot 2024-11-24 at 15 56 17](https://github.com/user-attachments/assets/9b6d461b-279f-4f73-8c0c-bdd99606f046)

## Cemu Metal version

Cemu `testing1.0.6.

## Mac

Mac Pro 2013 running macOS Ventura 13.7.1 using OpenCore Legacy Patcher

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
The game pad view seems like an issue with gamma correction. Could you please try setting a hotkey for switching to game pad view in the main window and see if the issue persists?

**Comment by bloedmage** [comment]
Colors are normal swapping the main screen to gamepad view. Second screen showing gamepad stays darker though.

<img width="1313" alt="Scherm­afbeelding 2024-11-24 om 20 51 18" src="https://github.com/user-attachments/assets/3bbb40ad-0338-4b68-bb08-716dc965f115">

**Comment by SamoZ256** [comment]
Does this bug occur in any other game?

**Comment by MickL** [comment]
> Game looks and plays great. Played only couple of minutes. 

A couple of minutes is not enough for this game. Did you play more in the meantime? With the non-metal version the problems came with particle effects that made the game unplayable even on Max chips. Ref: https://github.com/cemu-project/Cemu/issues/872

**Comment by SamoZ256** [comment]
> > Game looks and plays great. Played only couple of minutes. 
> 
> A couple of minutes is not enough for this game. Did you play more in the meantime? With the non-metal version the problems came with particle effects that made the game unplayable even on Max chips. Ref: https://github.com/cemu-project/Cemu/issues/872

The problem with particle effects is solved on Metal.

**Comment by bloedmage** [comment]
No FPS drops with particles on screen confirmed.

<img width="1392" height="860" alt="Image" src="https://github.com/user-attachments/assets/4aaec6e2-0eab-409f-84ea-48ef32eaa7cb" />

The game crashes Cemu sometimes. The only graphical bug I encountered playing the first two hours was some weird shadowing on one character when leaving the Tutorial island. 

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/149a9036-3418-4a11-8ad5-13b2b707a3c7" />
