### ISSUE TITLE
Batman Arkham City Armoured Edition

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#5]
## Description
InGame
Emulator crashes on second start, on first start it runs almost perfectly only some objects flicker
[log.txt](https://github.com/user-attachments/files/17732354/log.txt)

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1392" alt="Bildschirmfoto 2024-11-13 um 13 20 34" src="https://github.com/user-attachments/assets/6caebc46-91e4-4d9b-a72f-ee96e6c1bee0">

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.2
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Could you please clear the shader cache, run it again, and send the log? (Send it even if it doesn't crash)

**Comment by SamoZ256** [comment]
Did it crash after you have cleared the cache?

**Comment by darkuser89** [comment]
no, without a cache the game starts without problems but if a cache is available it crashes

**Comment by SamoZ256** [comment]
I see in the log that it fails to compile 2 pipeline states. That happens even without a shader cache, which indicates that errors when compiling pipelines from the cache aren't handled properly. Someone had the exact same issue in MK8 iirc. I will try to fix this.

**Comment by shinra-electric** [comment]
For me, it won't recognise any input (keyboard or controller). It just stays on the main menu saying "Press the + Button".
Input works on other games, though this is not the only one with this issue. 

[log.txt](https://github.com/user-attachments/files/17807054/log.txt)

**Comment by SamoZ256** [comment]
> For me, it won't recognise any input (keyboard or controller). It just stays on the main menu saying "Press the + Button". Input works on other games, though this is not the only one with this issue.
> 
> [log.txt](https://github.com/user-attachments/files/17807054/log.txt)

That’s strange. But I don’t think it has anything to do with Metal (or at least I hope)

**Comment by SamoZ256** [comment]
The crash should be fixed with testing1.0.5

**Comment by darkuser89** [comment]
> For me, it won't recognise any input (keyboard or controller). It just stays on the main menu saying "Press the + Button". Input works on other games, though this is not the only one with this issue.
> 
> [log.txt](https://github.com/user-attachments/files/17807054/log.txt)

You have to make sure that the Wii U gamepad is selected as the emulated gamepad; some games only recognize that as a gamepad.

**Comment by shinra-electric** [comment]
> You have to make sure that the Wii U gamepad is selected as the emulated gamepad; some games only recognize that as a gamepad.

Aha! That was the problem. Thanks.

**Comment by shinra-electric** [comment]
I noticed a new audio issue, probably not related to Metal. 
Alfred's voice doesn't play when talking to him over the radio. This is not mentioned on the wiki. 

The wiki also mentions that `GPUBufferCacheAccuracy` should be set to `0`, but I didn't do that and it's fine. (Not sure where to change that setting anyway...)

The game has slight issues with character faces and some objects, but this is mentioned in the Wiki so it's probably not Metal related either. 

Tested with `1.1.1`

![Screenshot 2024-12-19 at 13 29 52](https://github.com/user-attachments/assets/00a4a667-0a47-4471-a1df-33a301abcb0e)

**Comment by SamoZ256** [comment]
The buffer cache accuracy option was removed some time ago (a few years I believe)

**Comment by shinra-electric** [comment]
> Have you noticed the flickering that darkuser originally mentioned?

Yes, on some character faces and a couple of objects (like Penguin's knuckleduster). But this is what I was talking about above, it's mentioned in the wiki.

**Comment by SamoZ256** [comment]
Alright, so you say that the game doesn’t have any Metal specific issues?

**Comment by shinra-electric** [comment]
> Alright, so you say that the game doesn’t have any Metal specific issues?

That”s what I think….
😅

**Comment by SamoZ256** [comment]
Okay, I will close this then 🥳
