### ISSUE TITLE
Trine 2 Directors Cut

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#51]
## Description

`Perfect`

## Screenshots
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 05 50 23" src="https://github.com/user-attachments/assets/b7e3b0e8-f84e-485e-b389-e386bbbc268a">
<img width="1239" alt="Bildschirmfoto 2024-11-25 um 05 53 06" src="https://github.com/user-attachments/assets/ad053f53-e5a6-4cc2-9fca-322bf55955f2">

## Cemu Metal version

`testing1.0.6`

## Mac

M3 Pro MacBook Pro
## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Wow, these games have really beautiful art style. How come have I never heard of them 🙂
