### ISSUE TITLE
Dr Luigi

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#60]
## Description

`Playable`
[log.txt](https://github.com/user-attachments/files/18050050/log.txt)

## Screenshots
<img width="1113" alt="Bildschirmfoto 2024-12-07 um 23 20 30" src="https://github.com/user-attachments/assets/5552aaeb-8f40-49fa-9a60-96cf28e46266">
<img width="1157" alt="Bildschirmfoto 2024-12-07 um 23 19 13" src="https://github.com/user-attachments/assets/f68dc2ff-c8ef-4f91-a47a-323ebd351c06">
miss background
frame = https://www.mediafire.com/file/6t42pg1cvf0ekzr/Cemu_release.gputrace.7z/file

## Cemu Metal version

`testing1.0.6`

## Mac

M3 Pro 

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Is the log from the first run or was the shader cache already present?

**Comment by SamoZ256** [comment]
Could you please try [this build](https://drive.google.com/file/d/1lrTK2GDtkrrtJvz6QIF7VHyXu3D6C_Bp/view?usp=sharing)?

**Comment by darkuser89** [comment]
<img width="1160" alt="Bildschirmfoto 2024-12-08 um 15 42 46" src="https://github.com/user-attachments/assets/73fbda6c-6f1b-4406-b4ee-917fc7df81e2">
background works now

**Comment by SamoZ256** [comment]
Great! Are there any other issues?

**Comment by darkuser89** [comment]
no the game runs perfectly
