### ISSUE TITLE
Cars 3 

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#64]
## Description

`Boot`

## Screenshots
https://www.mediafire.com/file/87md7um81261y9h/cars.7z/file
same as infinity 2.0 maybe that helps too

## Cemu Metal version

`testing1.0.6`

## Mac

M3 Pro 

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Could you please do a frame capture with Vulkan? I see that everything gets rendered properly up to a point where it multiplies the color by 0.0

**Comment by darkuser89** [comment]
<img width="1160" alt="Bildschirmfoto 2024-12-08 um 17 20 51" src="https://github.com/user-attachments/assets/8c1fb54e-e574-4118-a389-f099b37b8112">
I can't manage to make a frame. It worked last time but not now

**Comment by darkuser89** [comment]
https://www.mediafire.com/file/36e8euxso5g09pn/cars3vulk.7z/file

**Comment by SamoZ256** [comment]
I just checked the Cemu wiki and it seems like it has black screen on Windows as well. The fact that half of the screen renders under Vulkan is due to missing geometry shaders

**Comment by darkuser89** [comment]
<img width="1160" alt="Bildschirmfoto 2024-12-08 um 22 16 38" src="https://github.com/user-attachments/assets/6665c9da-d337-4d4f-b76d-f700fda2950b">
Pressing A is all I can do then the game starts
