### ISSUE TITLE
Assassins Creed III

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#7]
## Description
InGame

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1392" alt="Bildschirmfoto 2024-11-13 um 13 40 03" src="https://github.com/user-attachments/assets/44b31aa1-71ff-4ee3-bb32-3228b7af77ee">
more pics https://imgur.com/a/pNqXyi1

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.2

Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by darkuser89** [comment]
Inframe = https://www.mediafire.com/file/f84oqwijmqse1h1/AC3.gputrace.zip/file

**Comment by SamoZ256** [comment]
I checked on Cemu wiki and it seems like it has the same issue with Vulkan.
