### ISSUE TITLE
Tekken Tag Tournament 2

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#72]
## Description

Screen freezes on character select screen when choosing second character. 
The game continues in the background, I can hear my inputs as the fight happens. 
[log.txt](https://github.com/user-attachments/files/18100353/log.txt)

No other issues spotted until this point. 

Edit: This issue does not occur on Vulkan.

## Screenshots
![Screenshot 2024-12-11 at 18 14 01](https://github.com/user-attachments/assets/cb4bed6f-4d31-4ac9-bb53-ac73f4196636)

## Cemu Metal version
`1.0.9`

## Mac
M1 Pro
macOS Sequoia 15.1.1

## Similar reports

- [ ] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
I really hope this is not a GPU hang like the last time with MK8 😳

**Comment by SamoZ256** [comment]
Isn't this a duplicate of #57? And if yes, could you please try with `testing1.0.6`?

**Comment by shinra-electric** [comment]
Ah, it's a duplicate.... Sorry.

I'll move the issue over there. 

I tried with `1.0.6` and can't get past the character select screen at all (tag or single mode).
