### ISSUE TITLE
Kung Fu Panda Showdown Of Legendary Legends

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#74]
## Description

`Perfect`

## Screenshots

<img width="1158" alt="Bildschirmfoto 2024-12-15 um 06 23 19" src="https://github.com/user-attachments/assets/8d89546b-2f6f-4e18-9c85-1bd560ed610e" />
<img width="1158" alt="Bildschirmfoto 2024-12-15 um 06 18 55" src="https://github.com/user-attachments/assets/1d0d97b5-8caf-463f-af49-98b080ab650c" />

## Cemu Metal version

`testing1.0.9`

## Mac

M3 Pro // 15.2

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
There is a Kung Fu Panda game?! I need it
