### ISSUE TITLE
Mario Sonic At The Sochi 2014 Olympic Winter Games

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#75]
## Description

`Boot`
[xcode.txt](https://github.com/user-attachments/files/18139134/xcode.txt)

## Screenshots
<img width="1158" alt="Bildschirmfoto 2024-12-15 um 06 59 04" src="https://github.com/user-attachments/assets/72cc146d-bd7a-416b-84cd-94bd684d6775" />
top left the wrong names of the countries are displayed and the font has errors
game gets stuck after you have chosen a country

## Cemu Metal version

`testing1.0.9`

## Mac

M3 Pro // 15.2

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
How does the game work with Vulkan? I checked the [Cemu wiki](https://wiki.cemu.info/wiki/Mario_%26_Sonic_at_the_Sochi_2014_Olympic_Winter_Games) and it seems like it has some problems on Windows as well. Does the audio continue after the game freezes?

**Comment by darkuser89** [comment]
yes it is the same as with vulkan
