### ISSUE TITLE
Hyrule Warriors

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#8]
## Description
InGame 
no graphics in the menu 
Shadow of the opponent not synchronized
[log.txt](https://github.com/user-attachments/files/17737315/log.txt)

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1392" alt="Bildschirmfoto 2024-11-13 um 18 58 08" src="https://github.com/user-attachments/assets/714bd4b1-6614-4261-a9b0-0a4eabd99b6e">
<img width="1392" alt="Bildschirmfoto 2024-11-13 um 19 00 32" src="https://github.com/user-attachments/assets/79b26ed3-ff82-4dd0-af42-77f6d7b5d0ad">

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.2

Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
What do you mean by shadows not being synchronized? Are they "detached" from the opponents?

**Comment by darkuser89** [comment]
yes the shadows are further away from the enemies than they should be
<img width="1392" alt="Bildschirmfoto 2024-11-13 um 19 45 20" src="https://github.com/user-attachments/assets/c9f70905-0416-493e-82b5-163a415e2e85">
also here at Link to see where his shadow is

**Comment by SamoZ256** [comment]
May I ask you to do a frame capture in the menu? (In case you have Xcode)

**Comment by darkuser89** [comment]
https://www.mediafire.com/file/h3xjo9udzzurar3/Cemu_release.gputrace.zip/file

hope that's right

**Comment by SamoZ256** [comment]
Thanks! Looks like the menu has the same issue as Ninja Gaiden 3.

**Comment by SamoZ256** [comment]
Could you please try out [this build](https://drive.google.com/file/d/1ShHt_Ujy8kHXyUPWFBKG27DRkdrU6-vz/view?usp=sharing)? It could fix the shadows.

**Comment by darkuser89** [comment]
<img width="1260" alt="Bildschirmfoto 2024-11-14 um 19 52 34" src="https://github.com/user-attachments/assets/513b7689-ffbe-49ad-b809-275be01ac9e0">
<img width="1260" alt="Bildschirmfoto 2024-11-14 um 19 53 19" src="https://github.com/user-attachments/assets/8eccff7e-cf44-4737-9386-b7f48a95e170">
<img width="1260" alt="Bildschirmfoto 2024-11-14 um 19 52 23" src="https://github.com/user-attachments/assets/3d696504-b2b6-4cbc-a93a-ff05889d771f">

wow that was quick yes now it works

**Comment by SamoZ256** [comment]
Are there any other issues? If not, I will label this as `perfect`.

**Comment by darkuser89** [comment]
[log.txt](https://github.com/user-attachments/files/17779281/log.txt)
no later in the game it crashes after completing later levels

**Comment by SamoZ256** [comment]
Oh well. I don’t think I can do anything with it rn sadly.

**Comment by darkuser89** [comment]
you can quit the game running I repeated some levels with version 1.0.3 and it doesn't support anymore

**Comment by SamoZ256** [comment]
You mean it doesn’t crash anymore?

**Comment by darkuser89** [comment]
I deleted the cache and repeated the levels and was able to complete the levels without the emulator crashing.

**Comment by SamoZ256** [comment]
I am going to label this as perfect if it doesn't crash anymore

**Comment by darkuser89** [comment]
you can set it to perfect, it works for me without any problems
