### ISSUE TITLE
Skylanders - Giants

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#82]
## Description

`Perfect`

## Screenshots
<img width="1392" alt="Bildschirmfoto 2024-12-16 um 22 58 57" src="https://github.com/user-attachments/assets/6206c716-223a-4516-ab25-216218331212" />
<img width="1392" alt="Bildschirmfoto 2024-12-16 um 22 54 49" src="https://github.com/user-attachments/assets/3a8f5f6f-899f-4c97-aab3-0a37a5cb76f1" />

## Cemu Metal version

`testing1.0.9`

## Mac

M3 Pro // 15.2 

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
👍
