### ISSUE TITLE
Bayonetta

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#84]
## Description
Playable, but requires `position invariance` option to fix striping/stippling on surfaces. 

Issue 1:
White screen on boot. Can be passed by pressing the `+` or `A` buttons. Same issue on Vulkan. 

Issue 2:
~~Minor issues with some particles being square and flashing. Not present on Vulkan. Same as Bayonetta 2 #43~~ Fixed 

Video of both issues: 

https://github.com/user-attachments/assets/b12157b1-d6f7-442c-8a3e-4f780505c8a9

## Screenshots
Screenshot of fixed surfaces: 
![Screenshot 2024-12-19 at 14 58 31](https://github.com/user-attachments/assets/b451ed1b-b881-4658-ab48-06b69dfd565d)

## Cemu Metal version
`testing1.1.1`

## Mac
M1 Pro
Sequoia 15.2

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
I really need to take a look at those square particles. Could you please make a frame capture?

**Comment by shinra-electric** [comment]
Here is a gpu trace for the white screen:
https://file.io/V3lFptuPZZ2P

I'll put one for the square particles on B2 because it's easier to capture.

**Comment by shinra-electric** [comment]
Square particles fixed with [this build](https://github.com/SamoZ256/cemu-metal-game-compatibility/issues/43#issuecomment-2558043729):
<img width="1392" alt="Screenshot 2024-12-21 at 10 50 42" src="https://github.com/user-attachments/assets/d60a4127-3d69-4de4-ac28-cb778d9a2320" />

**Comment by SamoZ256** [comment]
Great! The white screen seems to be an issue on Windows as well (according to Cemu wiki), but I am not entirely sure about that.

**Comment by shinra-electric** [comment]
Yeah, I saw a few mentions of that on the wiki. 
So I guess this is another perfect? 🤩

**Comment by SamoZ256** [comment]
There is always something to fix 🙃 Closing this issue 👍
