### ISSUE TITLE
Adventure Time: Explore the Dungeon Because I Don't Know!

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#86]
## Description
Perfect

## Screenshots
<img width="1392" alt="Screenshot 2024-12-23 at 09 36 56" src="https://github.com/user-attachments/assets/22b544d5-d820-472e-95e2-622732826954" />
<img width="1392" alt="Screenshot 2024-12-23 at 09 37 58" src="https://github.com/user-attachments/assets/c55e4fa5-ebd9-4ff8-8a4e-bd2b7a2b5ff2" />

## Cemu Metal version
`testing 1.1.1`

## Mac
M1 Pro
Sequoia 15.2

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
👍
