### ISSUE TITLE
Disney Planes

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#87]
## Description

`Playable`
works well but only with "position invariance"

## Screenshots
<img width="1392" alt="Bildschirmfoto 2024-12-23 um 13 36 04" src="https://github.com/user-attachments/assets/c3f2b785-0cfd-4326-ba9c-fcd738c2be65" />

## Cemu Metal version

`testing1.1.1`

## Mac

M3 Pro // 15.2

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Great! Have you noticed any issues?

**Comment by darkuser89** [comment]
I haven't noticed any errors so far, it's running well
