### ISSUE TITLE
Asdivine Hearts

### ISSUE THREAD

**Issue by shinra-electric** [SamoZ256/cemu-metal-game-compatibility#88]
## Description
Perfect

## Screenshots
![Screenshot 2024-12-23 at 14 19 02](https://github.com/user-attachments/assets/6cd0e078-c586-4af8-8cab-006746fa2e4f)
![Screenshot 2024-12-23 at 14 19 11](https://github.com/user-attachments/assets/6e3a3236-641e-479f-80e4-feb14f5d2ecb)

## Cemu Metal version
`1.1.1` 

## Mac
M1 Pro
Sequoia 15.2

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet

**Comment by SamoZ256** [comment]
Nice :)
