### ISSUE TITLE
Minecraft Story Mode The Complete Adventure

### ISSUE THREAD

**Issue by darkuser89** [SamoZ256/cemu-metal-game-compatibility#9]
## Description
InGame
a part of the screen is not rendered and black flickering on the characters

[log.txt](https://github.com/user-attachments/files/17774064/log.txt)

Describe the issues with the game (`Perfect` if none).

## Screenshots
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 11 23 33" src="https://github.com/user-attachments/assets/1fbd3030-e70d-4f63-b599-9e3cf14c7869">
<img width="1260" alt="Bildschirmfoto 2024-11-15 um 11 22 36" src="https://github.com/user-attachments/assets/25ad6fd2-a555-4750-9182-4ae0cba6ccb6">

Menu = https://www.mediafire.com/file/coxdvp39omuvxa6/minecraftstorygputrace.zip/file
Level Select = https://www.mediafire.com/file/bbetryqudcv5hme/level+select.gputrace.zip/file

Please include at least one screenshot of the game (if possible).

## Cemu Metal version
testing1.0.2
Put the version of Cemu you used for testing (e.g. `testing1.0.0`).

## Similar reports

- [X] I have checked that the game hasn’t been reported on the `Issues` page yet (please tick the checkbox by writing `X` inside `[ ]`)

**Comment by SamoZ256** [comment]
Does it work under Vulkan?

**Comment by darkuser89** [comment]
no with Vulkan there is only black screen from food to ingame

<img width="1260" alt="Bildschirmfoto 2024-11-15 um 16 51 11" src="https://github.com/user-attachments/assets/b65414d7-8388-4c73-92cc-67c4f6c233fc">

**Comment by SamoZ256** [comment]
Could you please turn on debug overlay and check `Triangle fans`?

**Comment by darkuser89** [comment]
do you mean that?

<img width="1260" alt="Bildschirmfoto 2024-11-15 um 17 30 50" src="https://github.com/user-attachments/assets/1d8f9134-56fa-48d7-b69f-6345ce9ec964">

**Comment by SamoZ256** [comment]
Could you please try out [this build](https://drive.google.com/file/d/1GiNmX_wY0Xw74Z24sffS7rHh18jJJcoa/view?usp=sharing)?

**Comment by darkuser89** [comment]
<img width="1260" alt="Bildschirmfoto 2024-11-16 um 14 58 21" src="https://github.com/user-attachments/assets/d7ac2eb7-adc6-4066-acb0-cb5a21c81d78">
<img width="1260" alt="Bildschirmfoto 2024-11-16 um 14 58 30" src="https://github.com/user-attachments/assets/13675472-4dc5-41b9-9658-87a408a92fa9">
yes the black triangle is gone only black flickering

**Comment by SamoZ256** [comment]
Could you please try turning fast math off and accurate barriers on? If it doesn’t help, I’d appreciate a frame capture

**Comment by SamoZ256** [comment]
And also, thank you for testing the Metal backend! You are helping a lot, there is no way I could’ve fixed all of these issues without your help

**Comment by darkuser89** [comment]
"Depth bias hack" from test build
<img width="1159" alt="Bildschirmfoto 2024-12-16 um 20 48 33" src="https://github.com/user-attachments/assets/2df75562-2078-4982-b1c8-684ef8b9919a" />
<img width="1159" alt="Bildschirmfoto 2024-12-16 um 20 48 26" src="https://github.com/user-attachments/assets/ecc01aa0-26cf-4663-a816-1f4e97a035fd" />
<img width="1159" alt="Bildschirmfoto 2024-12-16 um 20 48 10" src="https://github.com/user-attachments/assets/5e155219-678a-4175-a38d-097ee05a4064" />
unfortunately no improvement in the game. More black loading

**Comment by SamoZ256** [comment]
So the depth bias hack made it worse?

**Comment by darkuser89** [comment]
unfortunately I was hoping that it would be fixed like in resident evil

**Comment by SamoZ256** [comment]
Could you please do a frame capture (with the depth bias hack disabled)? I could see what exactly is the issue (I suspect the game uses it's own depth bias which doesn't go along nicely with the hack)

**Comment by darkuser89** [comment]
https://www.mediafire.com/file/kc9rnrjfytkd9d4/mcs1.7z/file

**Comment by darkuser89** [comment]
<img width="1392" alt="Bildschirmfoto 2024-12-18 um 17 00 30" src="https://github.com/user-attachments/assets/15073e8b-0cac-4dad-a236-b8731e799f17" />
<img width="1392" alt="Bildschirmfoto 2024-12-18 um 16 59 57" src="https://github.com/user-attachments/assets/0be13589-46e3-4b8f-b0cd-88dd1075b455" />
with test build 22 and new option it is fixed

**Comment by SamoZ256** [comment]
Great! Have you encountered any other issues?

**Comment by darkuser89** [comment]
no more problems. works well
